version: '3'

networks:
  app-net:

volumes:
  app-postgres:

services:
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: home
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    volumes:
      - app-postgres:/data/postgres
    networks:
      - app-net
    ports:
      - 5432:5432

  be:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: be
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    networks:
      - app-net
    depends_on:
      - db
