export { default as HomePage } from './home';
export { default as ChangePasswordPage } from './changepassword';
export { default as LoginPage } from './login';
export { default as ResetPasswordPage } from './resetpassword';
export { default as SignupPage } from './signup';
export { default as ChatListPage } from './chatlist';
export { default as FriendListPage } from './friendlist';
export { default as CallHistoryPage } from './callhistorylist';
export { default as ChatRoomPage } from './chatroom';
