export { default as Home } from './HomePage';
export { default as ChangePassword } from './ChangePasswordPage';
export { default as Login } from './LoginPage';
export { default as ResetPassword } from './ResetPasswordPage';
export { default as Signup } from './SignUpPage';
export { default as ChatList } from './ChatListPage';
export { default as FriendList } from './FriendListPage';
export { default as CallHistory } from './CallHistoryPage';
export { default as ChatRoom } from './ChatRoomPage';
