# Generated by Django 4.2 on 2023-04-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_username_customuser_firebase_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firebase_uid',
            new_name='username',
        ),
    ]
